<?php


namespace app\api\controller;


use think\Controller;
use think\Request;
use think\Db;

class Api extends Controller
{
    public $config;
    public $user_token;

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->config = Db::name("xitong")->where("id",1)->find()->toCollection();
        //判断登录
        $headers = Request::instance()->header();
        if(in_array('auth',$headers) && !empty($headers['auth'])){
            $info = Db::name("token")
                ->where("token",$headers["auth"])
                ->find()
                ->toCollection();
            if(empty($info)){
                $this->createError("未登录");
            }
            if(bcadd($info["expire_time"],$info["create_time"]) <= time()){
                $this->createError("登录超时");
            }
            $this->user_token = $info;
        }else{
            $this->createError("请登录后访问");
        }
    }

    /**
     * @param string $msg
     */
    public function createError($msg=''){
        $this->result('',0,$msg,'json');
    }

    /**
     * @param $data
     * @param string $msg
     */
    public function createSuccess($data,$msg=''){
        $this->result($data,0,$msg,'json');
    }
}