<?php
namespace app\api\controller;
use think\Db;
use think\Cookie;
use think\Session;
use think\Request;
use think\Exception;
/**
 * @title 用户中心
 * @description 接口说明
 */
class User extends Api{
    public $user_id;

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->user_id = $this->user_token->user_id;
    }

    /**
     * @title 获得用户信息
     * @description 获得用户新消息
     * @author 开发者
     * @url /api/user/getUserInfo
     * @method get
     * @return nickname:
     * @return headimg:http://www.xx.xx/xxx.png
     * @return status:1
     * @return phone:12312345678
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function getUserInfo(){
        $user_info = Db::name("user")->where("id",$this->user_id)->field("nickname,headimg,status,phone")->find();
        //咨询档案是否有新的消息

        //优惠券是否有临近过期

        //是否有新的分享
        return $user_info;
    }



}